SELECT HISTORY_ID, CAR_ID
     , TO_CHAR(START_DATE, 'yyyy-MM-dd') START_DATE
     , TO_CHAR(END_DATE, 'yyyy-MM-dd') END_DATE
     , CASE WHEN END_DATE - START_DATE + 1 < 30 THEN '단기 대여'
       ELSE '장기 대여' END RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= TO_DATE('20220901','yyyy-MM-dd')
AND START_DATE <= TO_DATE('20220930','yyyy-MM-dd')
ORDER BY HISTORY_ID DESC
;