SELECT UGB.TITLE, UGB.BOARD_ID, 
        UGR.REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS, 
        TO_CHAR(UGR.CREATED_DATE,'yyyy-MM-dd') CREATED_DATE
FROM USED_GOODS_BOARD UGB, USED_GOODS_REPLY UGR
WHERE UGB.BOARD_ID = UGR.BOARD_ID
AND TO_CHAR(UGB.CREATED_DATE, 'yyyyMM') = '202210'
ORDER BY UGR.CREATED_DATE, UGB.TITLE
;